#!/bin/bash

#touch ~/requirements.txt
#echo "numpy==1.10.4"	>> requirements.txt
#echo "scipy==0.16.1"	>> requirements.txt
#echo "Theano==0.8.0"	>> requirements.txt
#echo "Lasagne==0.2.dev1"	>> requirements.txt
#echo "joblib==0.9.3"	>> requirements.txt
#echo "scikit-learn==0.17"	>> requirements.txt
#echo "tabulate==0.7.5"	>> requirements.txt

pip install --user -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt
#pip install --user git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.7.git
pip install --user nolearn==0.6a0.dev0
pip install --upgrade --user theano
