#!/bin/bash

rm -rf ~/setup_nolearn_requirements.txt
touch ~/setup_nolearn_requirements.txt
echo "numpy==1.10.4"	>> requirements.txt
echo "scipy==0.16.1"	>> requirements.txt
echo "Theano==0.8.0"	>> requirements.txt
echo "-e git+https://github.com/Lasagne/Lasagne.git@master#egg=Lasagne==0.2.dev1.git"	>> requirements.txt
echo "joblib==0.9.3"	>> requirements.txt
echo "scikit-learn==0.17"	>> requirements.txt
echo "tabulate==0.7.5"	>> requirements.txt

cd ~
#pip install --user -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt
pip install --user -r ~/setup_nolearn_requirements.txt
pip install --user git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.6a0.dev0.git
pip install --upgrade --user theano

rm -rf ~/setup_nolearn_requirements.txt
